# Site settings
title: Prosecutor
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://prosecute.github.io" # the base hostname & protocol for your site
twitter_username: p
github_username:  prosecute

# Build settings
markdown: kramdown
relative_permalinks: false

t:
  en:
    header:
      download: "Download"  
      features: "Features"
      api: "API"        
      explore: "Explore"  
      prosecutorapi: "Prosecutor API" 
      prosecutorplanner: "Prosecutor Planner" 
      prosecutormoodle: "Prosecutor for Moodle" 
      barrister: "Barrister" 
      prosecutor: "API"
    title: "Prosecutor"
    description: "A free software solution for detecting plagiarism in source code."
    
  cs:
    header:
      download: "Ke stažení"  
      features: "Funkce"
      api: "API"        
      explore: "Prozkoumat"  
      prosecutorapi: "Prosecutor API" 
      prosecutorplanner: "Prosecutor Planner" 
      prosecutormoodle: "Prosecutor pro Moodle" 
      barrister: "Barrister" 
      prosecutor: "Prosecutor" 
      prosecutorproject: "Prosecutor projekt"
    title: "Prosecutor"
    description: "Open-source softwarové řešení pro detekci plagiátů ve zdrojových kódech."